USE Relations

--1 to 1
CREATE TABLE A (
ID INT IDENTITY(1,1),
Name NVARCHAR(20),
PRIMARY KEY(ID)
)

CREATE TABLE B (
ID INT IDENTITY(1,1),
Name NVARCHAR(20),
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES A(ID)
)

--1 to many
CREATE TABLE C (
ID INT IDENTITY(1,1),
Name NVARCHAR(20),
PRIMARY KEY(ID)
)

CREATE TABLE D (
ID INT IDENTITY(1,1),
ID_C INT,
Name NVARCHAR(20),
PRIMARY KEY(ID),
FOREIGN KEY(ID_C) REFERENCES C(ID)
)

--many to many
CREATE TABLE E (
ID INT IDENTITY(1,1),
Num INT,
PRIMARY KEY(ID)
)

CREATE TABLE F (
ID INT IDENTITY(1,1),
Num INT,
PRIMARY KEY(ID)
)

CREATE TABLE MID (
ID1 INT,
ID2 INT,
FOREIGN KEY(ID1) REFERENCES E(ID),
FOREIGN KEY(ID2) REFERENCES F(ID)
)

--recursive key
CREATE TABLE G (
ID INT IDENTITY(1,1),
PRIMARY KEY(ID),
FOREIGN KEY(ID) REFERENCES G(ID)
)